"""
HELPER CONFIG + SPRITE MANIFEST

The helper is the cosmetic companion on the dashboard. This module owns:

  a. The authoritative default - fresh installs get Joby.
  b. A sprite MANIFEST that points at animated GIFs served out of
     sentinel-ui/public/sprites/. Each sprite has multiple animation
     states (idle / celebrate / sleep) so the dashboard can switch
     the visible GIF based on user activity and milestones. Art is
     generated by scripts/build_sprites.py - regenerate whenever the
     palette or shape changes.
  c. The sayings catalogue - enough lines that the speech bubble
     doesn't repeat itself on a typical session.
  d. `validate_patch`, `resolve`, `read_helper`, `update_helper` so the
     UI gets a fully-populated renderable view every time.

All functions are pure. Persistence lives in user_store - helper is
stored as a nested dict under `user.helper`.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Optional


MAX_NAME_LENGTH = 20
MIN_NAME_LENGTH = 1

# Animation states every sprite ships. Grouped by role:
#   idle         — baseline loop
#   blink/look   — garnish woven into long idle stretches for liveness
#   nod/shake    — decision feedback (keep / skip in Blitz mode)
#   think        — shown while a pipeline cycle is actively running
#   eat          — fires when a fresh match feeds the helper
#   wave/bounce/celebrate — three tiers of arrow-key "petting" happiness
#   sleep        — drawn when the helper is starving / idle too long
# Order matters: the first entry is the default fallback when the
# frontend asks for a state that isn't in the manifest.
STATES: tuple[str, ...] = (
    "idle", "blink", "look", "nod", "shake", "think", "eat",
    "wave", "bounce", "celebrate", "sleep",
)
DEFAULT_STATE = "idle"

# Short bursts the frontend plays on top of the baseline state without
# canceling mood/pet logic. Keys are the state names, values are the
# approximate display duration in ms. Server-side only advisory - the
# UI reads these from /api/helper/options to pace its overlays.
BURST_MS: dict[str, int] = {
    "blink":  300,
    "look":   660,
    "nod":    420,
    "shake":  440,
    "eat":    480,
    "think": 1800,  # longer because it usually fills an in-progress window
}

# Happy tiers exposed to the frontend. Ordered low -> high. The UI maps
# a "happiness" counter to the largest tier whose threshold is <= it.
# Kept here (not in App.jsx) so the backend is the source of truth and
# the help/settings UI can show accurate thresholds.
HAPPY_TIERS: tuple[dict, ...] = (
    {"state": "wave",      "min": 1, "mood": "pet_wave"},
    {"state": "bounce",    "min": 3, "mood": "pet_bounce"},
    {"state": "celebrate", "min": 6, "mood": "pet_celebrate"},
)

EYE_STYLES: tuple[str, ...] = ("dots", "happy", "focus", "sleepy")
ACCESSORIES: tuple[str, ...] = ("none", "beanie", "headphones", "glasses")


def _assets_for(key: str) -> dict[str, str]:
    """Build the standard state-to-asset-url map for a sprite key.

    Filenames follow the convention `{key}_{state}.gif` under
    sentinel-ui/public/sprites/ - see scripts/build_sprites.py."""
    return {state: f"/sprites/{key}_{state}.gif" for state in STATES}


# Sprite manifest. `assets` is a state->url dict so the frontend can
# swap between idle/celebrate/sleep GIFs without an extra round-trip.
# Adding a new sprite is a two-step: add frames to
# scripts/build_sprites.py (gets you the GIFs) and add an entry here.
# The frontend falls back to a coloured placeholder if a GIF 404s, so
# a half-configured manifest doesn't break the dashboard.
SPRITES: dict[str, dict] = {
    "joby": {
        "label": "Joby",
        "description": "A round peach blob. The default.",
        "assets": _assets_for("joby"),
        "credit": "Procedurally drawn — scripts/build_sprites.py",
    },
    "rollo": {
        "label": "Rollo",
        "description": "A scruffy pixel dog.",
        "assets": _assets_for("rollo"),
        "credit": "Procedurally drawn — scripts/build_sprites.py",
    },
    "momo": {
        "label": "Momo",
        "description": "A tabby pixel cat.",
        "assets": _assets_for("momo"),
        "credit": "Procedurally drawn — scripts/build_sprites.py",
    },
    "hoot": {
        "label": "Hoot",
        "description": "A pixel owl. Watchful, recon energy.",
        "assets": _assets_for("hoot"),
        "credit": "Procedurally drawn — scripts/build_sprites.py",
    },
    "slim": {
        "label": "Slim",
        "description": "A bouncy slime. Keeps its shape under pressure.",
        "assets": _assets_for("slim"),
        "credit": "Procedurally drawn — scripts/build_sprites.py",
    },
    "pixel": {
        "label": "Pixel",
        "description": "A boxy retro robot. Beeps in JSON.",
        "assets": _assets_for("pixel"),
        "credit": "Procedurally drawn — scripts/build_sprites.py",
    },
}

DEFAULT_SPRITE = "joby"

DEFAULT_HELPER: dict = {
    "name": "Joby",
    "sprite": DEFAULT_SPRITE,
    "eyes": "dots",
    "accessory": "none",
}


# Sayings grouped by mood. UI picks contextually and shuffles within
# the group so the same line doesn't repeat.
SAYINGS: dict[str, list[str]] = {
    "idle": [
        "Want me to check the boards?",
        "Coffee break. Ready when you are.",
        "Just vibing. Click Run Pipeline any time.",
        "Reading resumes for fun.",
        "The job market never sleeps. I only kinda sleep.",
        "New week, new matches. Maybe.",
        "I practiced my interview handshake. Looks great.",
        "Refreshed my browser history of heartbreak.",
        "Watching the cursor blink. Peaceful.",
        "Noticed you're online. No pressure.",
        "I organised your rejections by colour.",
        "Tell me when.",
        "Pretending to read a book.",
        "Counting commits instead of sheep.",
        "If a tree falls in the job board...",
        "Got my walking shoes on.",
        "Kept a streak of zero complaints.",
        "Offers don't apply to themselves.",
        "Running diagnostic: mood OK, ears perky.",
        "Ready whenever.",
    ],
    "cycle_start": [
        "On it. Fetching fresh postings.",
        "Cycle up. Boards in sight.",
        "Sniffing for roles.",
        "Going hunting. Back shortly.",
        "Scraping responsibly, I promise.",
        "Putting on my detective hat.",
        "Don't wait up.",
        "Let's find you something good.",
    ],
    "match_found": [
        "New match. Have a look.",
        "Found one worth a read.",
        "This one looks promising.",
        "Your taste + this role = yes?",
        "Flagging this. Seems aligned.",
        "Saved you a click - this one's close.",
    ],
    "empty_cycle": [
        "Boards were quiet. No new fits.",
        "Nothing new in your wheelhouse today.",
        "Clean sweep, nothing above threshold.",
        "The boards ghosted us. Rude.",
        "Quiet day. Tomorrow's another try.",
    ],
    "encourage": [
        "You're more qualified than the job post implies.",
        "Rejection is a recruiter-side problem.",
        "One yes changes everything.",
        "Your resume is better than you think it is.",
        "Volume beats perfection. Keep sending.",
        "The right role is still out there.",
        "Don't take the silence personally.",
        "Every application is a lesson filed.",
    ],
    "celebrate": [
        "We did it!",
        "Milestone unlocked. Take the win.",
        "That's a streak worth keeping.",
        "Proof the work compounds.",
        "Today's a good day to keep going.",
        "You earned this moment.",
    ],
    # Tier-1 pet: small "oh hi" acknowledgements. Low-key on purpose so
    # mashing arrow keys doesn't feel performative.
    "pet_wave": [
        "oh hi",
        "*wiggles*",
        "hey you",
        "tickle spot found",
        "aw thanks",
        "nice to see you",
        "*little wave*",
        "you noticed me",
        "*bashful*",
        "right back at ya",
        "petting acknowledged",
        "hehe",
    ],
    # Tier-2 pet: visibly pleased. A step up in energy.
    "pet_bounce": [
        "yes yes yes",
        "MORE of that please",
        "boingy boingy",
        "this is my good day",
        "you are my favourite",
        "*happy chirp*",
        "warm fuzzies activated",
        "we're having fun now",
        "that hit the spot",
        "keep 'em coming",
        "*bounces on the spot*",
        "endorphins: deployed",
    ],
    # Tier-3 pet: maxed out. Over-the-top language.
    "pet_celebrate": [
        "AMAZING",
        "BEST DAY EVER",
        "I LOVE THIS JOB",
        "we are UNSTOPPABLE",
        "YIPPEEEEE",
        "TEN OUT OF TEN",
        "PEAK SEROTONIN",
        "LEGENDARY ENERGY",
        "MAXIMUM JOBY",
        "THIS IS THE WAY",
    ],
    # Keep-decision feedback. Short approving lines paired with the nod.
    "decision_keep": [
        "good one!",
        "nice pick",
        "filing that",
        "locked in",
        "agreed",
        "yep, solid",
        "shortlist it is",
        "you've got taste",
        "sensible",
        "marked",
    ],
    # Skip-decision feedback. Neutral, not sassy - we don't want to shame
    # the user for passing.
    "decision_skip": [
        "fair enough",
        "next",
        "onwards",
        "no worries",
        "not our vibe",
        "pass noted",
        "moving on",
        "understood",
        "skip registered",
        "roger that",
    ],
    # Pipeline cycle running. Shown while the helper plays the 'think'
    # animation. Keep them calm - nothing worse than a chatty bot while
    # you're watching a progress bar.
    "cycle_working": [
        "crawling the boards...",
        "checking in with the APIs",
        "rummaging through postings",
        "reading carefully",
        "scoring the batch",
        "putting together a list",
        "won't be long",
        "triangulating matches",
    ],
    # New match arrived - sibling of match_found but shorter, paired
    # with the eat animation. Think of this as a munch-and-smile.
    "match_eat": [
        "mm, tasty role",
        "nom nom",
        "filed this one away",
        "that's a good one",
        "saving it for you",
        "added to the pile",
        "crunchy",
    ],
}


@dataclass(frozen=True)
class HelperView:
    """Serialisable view used by /api/helper. `assets` is the full
    state->url map so the frontend can swap animations locally without
    refetching. `asset_url` is the convenience default (idle state) for
    simple renderers."""
    name: str
    sprite: str
    eyes: str
    accessory: str
    asset_url: str
    assets: dict[str, str]
    label: str
    credit: str

    def to_dict(self) -> dict:
        return {
            "name": self.name,
            "sprite": self.sprite,
            "eyes": self.eyes,
            "accessory": self.accessory,
            "asset_url": self.asset_url,
            "assets": dict(self.assets),
            "label": self.label,
            "credit": self.credit,
        }


def default_helper() -> dict:
    """Fresh independent copy of the default helper."""
    return dict(DEFAULT_HELPER)


def _clean_name(raw: Any) -> Optional[str]:
    if not isinstance(raw, str):
        return None
    name = raw.strip()
    if not name:
        return None
    return name[:MAX_NAME_LENGTH]


def validate_patch(patch: Any) -> dict:
    """Return a dict safe to merge into stored helper state. Unknown
    keys dropped. Out-of-range values dropped (not clamped) so a bad
    patch is a no-op rather than a silent reset."""
    if not isinstance(patch, dict):
        return {}
    cleaned: dict = {}
    if "name" in patch:
        name = _clean_name(patch["name"])
        if name is not None:
            cleaned["name"] = name
    if "sprite" in patch and patch["sprite"] in SPRITES:
        cleaned["sprite"] = patch["sprite"]
    if "eyes" in patch and patch["eyes"] in EYE_STYLES:
        cleaned["eyes"] = patch["eyes"]
    if "accessory" in patch and patch["accessory"] in ACCESSORIES:
        cleaned["accessory"] = patch["accessory"]
    return cleaned


def resolve(stored: Any) -> HelperView:
    """Merge stored helper dict with defaults, attach sprite metadata.
    Always returns a renderable view."""
    merged = default_helper()
    if isinstance(stored, dict):
        merged.update(validate_patch(stored))
    sprite_data = SPRITES.get(merged["sprite"]) or SPRITES[DEFAULT_SPRITE]
    assets = dict(sprite_data["assets"])
    return HelperView(
        name=merged["name"],
        sprite=merged["sprite"],
        eyes=merged["eyes"],
        accessory=merged["accessory"],
        asset_url=assets[DEFAULT_STATE],
        assets=assets,
        label=sprite_data["label"],
        credit=sprite_data["credit"],
    )


def read_helper(data_dir) -> HelperView:
    from core import user_store
    try:
        user = user_store.load(data_dir)
    except Exception:
        user = {}
    return resolve((user or {}).get("helper"))


def update_helper(data_dir, patch: Any) -> HelperView:
    from core import user_store
    cleaned = validate_patch(patch)
    current = user_store.load(data_dir)
    existing = current.get("helper") if isinstance(current.get("helper"), dict) else {}
    merged = dict(existing or default_helper())
    merged.update(cleaned)
    user_store.update(data_dir, {"helper": merged})
    return resolve(merged)


def list_options() -> dict:
    """Everything the settings UI needs. Sprite entries include the
    full state->asset map so the picker can preview idle animations
    and hint at celebrate/sleep variants."""
    return {
        "sprites": [
            {
                "key": key,
                "label": data["label"],
                "description": data["description"],
                "assets": dict(data["assets"]),
                "asset_url": data["assets"][DEFAULT_STATE],
                "credit": data["credit"],
            }
            for key, data in SPRITES.items()
        ],
        "eyes": list(EYE_STYLES),
        "accessories": list(ACCESSORIES),
        "states": list(STATES),
        "happy_tiers": [dict(t) for t in HAPPY_TIERS],
        "burst_ms": dict(BURST_MS),
        "name_limits": {"min": MIN_NAME_LENGTH, "max": MAX_NAME_LENGTH},
        "default": dict(DEFAULT_HELPER),
    }


def sayings(mood: str = "idle") -> list[str]:
    """Return the saying list for a mood, or the idle list if unknown."""
    return list(SAYINGS.get(mood) or SAYINGS["idle"])
