"""
STAR+R Story Bank
=================

What this file is
-----------------
Every time we analyze a matched job, we ask a tiny LLM to turn the
role's "talking_points" (generated by the fit-gap analyzer) into
STAR+R-shaped bullets (Situation, Task, Action, Result, Reflection)
that the user can paste straight into an interview prep doc.

We APPEND those bullets to a single markdown file:

    data/story_bank.md

Each bullet is tagged so the user can later grep or filter:

    ## [ai_pm] Anthropic — Senior Product Manager, Applied AI
    _added 2026-04-23 · match 87%_

    - **S/T:** ...
    - **A:**   ...
    - **R:**   ...
    - **R:**   ...  (reflection / what you'd do differently)

Why a plain markdown file?
--------------------------
The user is not technical. Markdown opens in any text editor and
any viewer (VSCode, Obsidian, GitHub). No migrations, no schema, no
database. If the format needs to change, it's a Find & Replace.

Why is this in core/ and not agents/?
-------------------------------------
Because it's a pure storage utility -- no LLM calls live here. The
LLM step that GENERATES bullets lives in the analyzer path. This file
only knows how to format and append.

Safety
------
We use core.io_safe.write_json_atomic-style discipline: write to a
tmpfile and rename. Markdown isn't JSON, so we call the simpler
pathlib+replace dance inline. See _atomic_append below.
"""

from __future__ import annotations

import logging
import os
import re
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

logger = logging.getLogger("sentinel.story_bank")


# Default filename inside whatever data_dir the caller passes.
DEFAULT_FILENAME = "story_bank.md"

# Header block written once at the top of the file the first time we
# create it. Keeps a plain-text explanation within reach of the user.
FILE_HEADER = """# Sentinel Story Bank

Interview-ready STAR+R bullets, appended automatically every time
Sentinel runs a fit-gap analysis on a matched job. Each entry is
tagged with the role archetype and company so you can grep later:

    grep "\\[ai_pm\\]" story_bank.md

Format per entry:
- **S/T:** Situation + Task (one sentence)
- **A:**   Action you took
- **R:**   Result (metric / outcome)
- **R:**   Reflection (what you'd do again or differently)

Entries are deduped by a URL+archetype key, so re-running analysis on
the same job won't spam this file.

---
"""


def append_stories(
    *,
    data_dir: str | Path,
    job: dict[str, Any],
    analysis: dict[str, Any],
    bullets: list[dict[str, str]] | None = None,
) -> Path | None:
    """Append a STAR+R section for one analyzed job to the story bank.

    Parameters
    ----------
    data_dir :
        The Sentinel data directory. Story bank lives at
        <data_dir>/story_bank.md.
    job :
        The job payload dict. We read title, company, url, archetype,
        _match_score. Missing fields degrade gracefully.
    analysis :
        The fit-gap analyzer's result dict. We read talking_points and
        match_percentage.
    bullets :
        Optional pre-built list of STAR+R bullets. If None, we fall
        back to formatting whatever talking_points are in `analysis`
        into a simpler single-bullet block. This lets callers who
        haven't wired the LLM-rewriter yet still populate the bank.

    Returns
    -------
    Path to the story_bank file on success, or None if we skipped
    (e.g. duplicate entry) or failed. Never raises.
    """
    try:
        data_path = Path(data_dir)
        data_path.mkdir(parents=True, exist_ok=True)
        fpath = data_path / DEFAULT_FILENAME

        # Build the entry first so we can compute the dedup key.
        entry_text, entry_key = _format_entry(job=job, analysis=analysis, bullets=bullets)
        if not entry_text:
            # Nothing worth writing (e.g. no talking_points and no bullets).
            return None

        # Skip if this exact (url, archetype) pair is already in the file.
        # Cheap linear scan -- the file is tiny compared to RAM and we'd
        # rather stay obvious than build an index.
        if fpath.exists() and _already_contains(fpath, entry_key):
            logger.info("[story_bank] skip duplicate: %s", entry_key)
            return fpath

        # Initialize the file with a header on first write.
        if not fpath.exists():
            _atomic_write_text(fpath, FILE_HEADER)

        _atomic_append(fpath, entry_text)
        logger.info("[story_bank] appended: %s", entry_key)
        return fpath

    except Exception as e:
        # Never let the story bank kill the analysis pipeline.
        logger.warning("[story_bank] write failed: %s", e)
        return None


# -----------------------------------------------------------------------------
# INTERNALS
# -----------------------------------------------------------------------------

def _format_entry(
    *,
    job: dict[str, Any],
    analysis: dict[str, Any],
    bullets: list[dict[str, str]] | None,
) -> tuple[str, str]:
    """Build the markdown block for one job analysis.

    Returns (text, dedup_key). If there's nothing to write, text is "".
    """
    title = (job.get("title") or "Untitled role").strip()
    company = (job.get("company") or "Unknown company").strip()
    url = (job.get("url") or "").strip()
    archetype = (job.get("archetype") or "unclassified").strip()

    # Prefer the analyzer's computed match_percentage; fall back to the
    # cosine-driven _match_score scaled to 0-100.
    match_pct = analysis.get("match_percentage")
    if match_pct is None:
        raw = job.get("_match_score", 0.0) or 0.0
        match_pct = int(round(float(raw) * 100))

    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    # Dedup key: stable identity for "this job, this archetype".
    # Matches what _already_contains greps for. Including archetype
    # means a re-classified job DOES get a fresh entry.
    dedup_key = f"key:{archetype}:{url or f'{company}:{title}'}"

    # Pull or synthesize bullets.
    if bullets is None:
        bullets = _bullets_from_talking_points(
            analysis.get("talking_points") or []
        )
    if not bullets:
        return "", dedup_key

    # Markdown assembly. Single f-string, readable top-to-bottom.
    url_line = f" · [link]({url})" if url else ""
    lines = [
        "",  # blank line before heading
        f"## [{archetype}] {company} — {title}",
        f"_added {today} · match {match_pct}%{url_line}_",
        f"<!-- {dedup_key} -->",
        "",
    ]

    for b in bullets:
        st = (b.get("st") or b.get("situation_task") or "").strip()
        action = (b.get("a") or b.get("action") or "").strip()
        result = (b.get("r") or b.get("result") or "").strip()
        reflection = (b.get("reflection") or b.get("rr") or "").strip()

        # Omit missing parts rather than writing empty bullets.
        if st:
            lines.append(f"- **S/T:** {st}")
        if action:
            lines.append(f"- **A:**   {action}")
        if result:
            lines.append(f"- **R:**   {result}")
        if reflection:
            lines.append(f"- **R:**   {reflection}")
        lines.append("")  # blank line between bullets

    lines.append("---")
    lines.append("")

    return "\n".join(lines), dedup_key


def _bullets_from_talking_points(points: list[str]) -> list[dict[str, str]]:
    """Turn raw talking_points strings into minimal STAR+R stubs.

    This is the fallback when no LLM rewriter is wired yet. We keep
    each point as the "A" (action) slot and leave S/T/R/R empty.
    The user sees a starter bullet to flesh out rather than nothing.
    """
    out = []
    for raw in points:
        s = (raw or "").strip()
        if not s:
            continue
        out.append({"a": s})
    return out


def _already_contains(fpath: Path, dedup_key: str) -> bool:
    """Grep the file for the dedup HTML comment. True if present."""
    try:
        needle = f"<!-- {dedup_key} -->"
        # File is markdown, typically small (<1MB). Read once.
        text = fpath.read_text(encoding="utf-8", errors="replace")
        return needle in text
    except Exception:
        return False


def _atomic_write_text(fpath: Path, text: str) -> None:
    """Write a file atomically (temp + rename). Keeps the bank from
    being half-written if the process is killed mid-write."""
    tmp_fd, tmp_path = tempfile.mkstemp(dir=str(fpath.parent), suffix=".tmp")
    try:
        with os.fdopen(tmp_fd, "w", encoding="utf-8") as f:
            f.write(text)
        os.replace(tmp_path, fpath)
    except Exception:
        # Clean up the orphan temp file on any failure.
        try:
            os.unlink(tmp_path)
        except Exception:
            pass
        raise


def _atomic_append(fpath: Path, text: str) -> None:
    """Atomic append = read old, write old+new to tmp, rename.

    Cheap because the file stays small. Avoids the interleaving issue
    a plain open(..., 'a') has if two cycles land on the same bank.
    """
    existing = fpath.read_text(encoding="utf-8", errors="replace") if fpath.exists() else ""
    _atomic_write_text(fpath, existing + text)
